export const TODO_LIST_REQ="TODO_LIST_REQ";
export const TODO_LIST_SUCCESS="TODO_LIST_SUCCESS";
export const TODO_LIST_FAIL="TODO_LIST_FAIL";

export const TODO_ADD_REQ="TODO_ADD_REQ";
export const TODO_ADD_SUCCESS="TODO_ADD_SUCCESS";
export const TODO_ADD_FAIL="TODO_ADD_FAIL";

export const TODO_DEL_REQ="TODO_DEL_REQ";
export const TODO_DEL_SUCCESS="TODO_DEL_SUCCESS";
export const TODO_DEL_FAIL="TODO_DEL_FAIL";

export const TODO_UPDATE_REQ="TODO_UPDATE_REQ";
export const TODO_UPDATE_SUCCESS="TODO_UPDATE_SUCCESS";
export const TODO_UPDATE_FAIL="TODO_UPDATE_FAIL";

export const USER_REG_REQ="USER_REG_REQ";
export const USER_REG_SUCCESS="USER_REG_SUCCESS";
export const USER_REG_FAIL="USER_REG_FAIL";

export const USER_LOGIN_REQ="USER_LOGIN_REQ";
export const USER_LOGIN_SUCCESS="USER_LOGIN_SUCCESS";
export const USER_LOGIN_FAIL="USER_LOGIN_FAIL";

export const USER_LOGOUT_REQ="USER_LOGOUT_REQ";
export const USER_LOGOUT_SUCCESS="USER_LOGOUT_SUCCESS";
export const USER_LOGOUT_FAIL="USER_LOGOUT_FAIL";

export const USER_INFO_REQ="USER_INFO_REQ";
export const USER_INFO_SUCCESS="USER_INFO_SUCCESS";
export const USER_INFO_FAIL="USER_INFO_FAIL";